[fix] filename could contain illegal char
lightly-ai/labelformat pull request #7
Opened 2023-11-02 14:28 UTC by Joilence

**Issue:** #6 

Previous code used `global_key` or `external_id` as filename, but according to LabelBox documentation, they could contain illegal characters for a filename, e.g. a POSIX path separator `/`, which leads to an unexpected file path when used as a filename.

**Improvement as follows:**

1. offer an option to specify which key (among `global_key`, `external_id` and `id`) in data_row to use as filename.
2. when `filename_key` is not specified, try different options as previous code did, but also check for illegal characters.
3. default behavior (when `filename_key` is not give) is mostly not changed.

2023-11-03 10:01 UTC, michal-lightly requested changes
Thanks a lot for submitting a PR! There are a few changes needed. If you'd like, you can implement them, or let us know and we'll take over the PR.

After they are implemented, there are a few more steps that we intend to take care of:
* Make the [static checks and tests](https://github.com/lightly-ai/labelformat#development) pass
* Allow setting the filename_key with CLI

Again, if you'd like to do that yourself let us know and we can provide pointers.

2023-11-03 10:01 UTC, michal-lightly commented on src/labelformat/formats/labelbox.py
> +    def get_labels(self, filename_key: str = None) -> Iterable[ImageObjectDetection]:
Because `LabelboxObjectDetectionInput` is implementing `ObjectDetectionInput`, the signature of `get_labels()` cannot change. Instead, we have to pass `filename_key` to the initialiser and store it as a class attribute.

2023-11-03 10:01 UTC, michal-lightly commented on src/labelformat/formats/labelbox.py
> +            f"Filename key '{filename_key}' does not exist in data_row: {data_row['data_row']}"
The first assert can be moved to the initialiser when `filename_key` is passed there.

A stylistic note: We use `ParseError` throughout the code so that it is easier to catch by potential callers.

2023-11-03 10:01 UTC, michal-lightly commented on src/labelformat/formats/labelbox.py
> +                break
With this extended logic, it can happen that when a user adds a new file to the dataset that contains an illegal character, the output filenames could suddenly change e.g. from global key to id.

I suggest to instead set global key as the default. The user will be notified with the error message to use a different option if it contains an illegal character.

2023-11-13 09:39 UTC, michal-lightly requested changes
Thanks @IgorSusmelj , it looks good! We also need to expose the parameter in cli.

I'll make the final changes and merge.

2023-11-13 09:39 UTC, michal-lightly commented on src/labelformat/formats/labelbox.py
> +FILENAME_KEYS = ["global_key", "external_id", "id"]  # valid filename keys
We can improve this by using an Enum.

2023-11-13 09:39 UTC, michal-lightly commented on tests/unit/formats/test_labelbox.py
> +class TestLabelboxFunctions:
Style: We adopted the style used in some public python libraries like `requests`. The tests are in the public scope, we group them in a class only for testing class methods. I'll adjust.

2023-11-13 10:29 UTC, michal-lightly approved these changes
Thanks @Joilence and @IgorSusmelj !

2023-11-13 10:29 UTC, merged

2023-11-19 19:29 UTC, Joilence commented
@IgorSusmelj Thanks, sorry for the late reply!